site_name: Open Undergraduate Math Solutions
site_url: https://brasarlington.github.io/open-undergraduate-math-books-solutions/
repo_url: https://github.com/brasarlington/open-undergraduate-math-books-solutions
edit_uri: edit/main/docs/ # Esto agrega un botón "Edit this page"

theme:
  name: material
  language: en # Cambiamos a inglés
  palette:
    scheme: default
    primary: indigo
    accent: teal
  features:
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - tables
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Set Theory:
    -Charles Pinter: 
        - Chapter 1: set-theory/pinter/chapter1.md
        - Chapter 2: set-theory/pinter/chapter2.md
        - Chapter 3: set-theory/pinter/chapter3.md
        - Chapter 4: set-theory/pinter/chapter4.md
        - Chapter 5: set-theory/pinter/chapter5.md
        - Chapter 6: set-theory/pinter/chapter6.md
        - Chapter 7: set-theory/pinter/chapter7.md
        - Chapter 8: set-theory/pinter/chapter8.md
        - Chapter 9: set-theory/pinter/chapter9.md
        - Chapter 10: set-theory/pinter/chapter10.md
        - Chapter 11: set-theory/pinter/chapter11.md

  # Nueva sección de Análisis
  - Analysis:
      - Walter Rudin:
        - 'Chapter 1 - Real Numbers': analysis/rudin/chapter1.md
