site_name: Open Undergraduate Math Solutions
site_url: https://brasarlington.github.io/open-undergraduate-math-books-solutions/
repo_url: https://github.com/brasarlington/open-undergraduate-math-books-solutions
edit_uri: edit/main/docs/ # Esto agrega un botón "Edit this page"

theme:
  name: material
  language: en # Cambiamos a inglés
  palette:
    scheme: default
    primary: indigo
    accent: teal
  features:
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - tables
  - admonition

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

#nav:
 # - Home: index.md
  #- Set Theory:
   # - 'Charles Pinter - Chapter 1': set-theory/pinter/chapter1.md
